{% set version = "2.0.9" %}

package:
  name: ecos
  version: {{ version }}

source:
  # cannot use PyPI, because no wheels have been published, see discussion here:
  # https://github.com/embotech/ecos-python/commit/97db46bc65e243c75eadc06d36e36dcedce92f8c
  - url: https://github.com/embotech/ecos-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 2291459e95c5e11146306f6dc2cdf5f99aeee1777a6b38c409bc8ce009ff1512
  # include submodule (not in github tarball due to dear-github/dear-github#214)
  - git_url: https://github.com/embotech/ecos.git
    git_rev: v2.0.8
    folder: ecos

build:
  number: 0
  script: make version && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1

test:
  requires:
    - nose
  imports:
    - ecos
    - _ecos
  source_files:
    - src/test_interface.py
    - src/test_interface_bb.py
  commands:
    - python src/test_interface.py
    - python src/test_interface_bb.py

about:
  home: https://github.com/embotech/ecos
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # in recipe for now; https://github.com/embotech/ecos-python/pull/15
  summary: Python interface for ECOS, a lightweight conic solver for second-order cone programming
  dev_url: https://github.com/embotech/ecos-python

extra:
  recipe-maintainers:
    - djsutherland
    - h-vetinari
