{% set version = "2.0.11" %}
# only python bindings got version 2.0.11, core lib unchanged
{% set version_core = "2.0.10" %}

package:
  name: ecos
  version: {{ version }}

source:
  - url: https://github.com/embotech/ecos-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 01ebd3fc8a54822e035c5d69f750fc577001754a057a6a023b68e736c43a7823
  # include submodule (not in github tarball due to dear-github/dear-github#214)
  - git_url: https://github.com/embotech/ecos.git
    git_rev: v{{ version_core }}
    folder: ecos

build:
  number: 1
  script: make version && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.1

test:
  requires:
    - pytest
  imports:
    - ecos
    - _ecos
  source_files:
    - src/test_interface.py
    - src/test_interface_bb.py
  commands:
    - python src/test_interface.py
    - python src/test_interface_bb.py

about:
  home: https://github.com/embotech/ecos
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # in recipe for now; https://github.com/embotech/ecos-python/pull/15
  summary: Python interface for ECOS, a lightweight conic solver for second-order cone programming
  dev_url: https://github.com/embotech/ecos-python

extra:
  recipe-maintainers:
    - djsutherland
    - h-vetinari
